
POST http://localhost:3333/videos
Content-Type: application/json


{
  "title": "Video 2542",
  "url": "cdoase",
  "duration": "5728"
}

###

GET http://localhost:3333/videos


###

PUT  http://localhost:3333/videos/1725752478987
Content-Type: application/json


{
  "title": "Video 1255",
  "url": "lllnaavab",
  "duration": "257"
}

###

DELETE http://localhost:3333/videos/1726006754609
Content-Type: application/json


# {
#   "title": "Video 05",
#   "url": "dhjhgfhjfaa",
#   "duration": "105"
# }