
POST http://localhost:3333/videos
Content-Type: application/json


{
  "title": "Video 2020",
  "url": "criszaretdgfdo",
  "duration": "11222"
}

###

GET http://localhost:3333/videos


###

PUT  http://localhost:3333/videos/1725747738923
Content-Type: application/json


{
  "title": "Video 125",
  "url": "lllfadnaava",
  "duration": "1225"
}

###

DELETE http://localhost:3333/videos/1725747738923
Content-Type: application/json


{
  "title": "Video 05",
  "url": "dhjhgfhjfaa",
  "duration": "105"
}